### ISSUE TITLE
Sometimes svg is not injected

### ISSUE THREAD

**Issue by prlyons** [tanem/svg-injector#1061]
Sorry my code is behind a firewall so it is not available to run an example. I have a page where I use the same svg source in multiple places but sometimes the svg fails to be injected. Instead I get the following div.

`<div data-src="Pub/Web/Icon/arrowDropDown.svg" src(unknown)></div>`

If I perform an action to cause the svg container to render again the svg will show. I am running on a web server not locally. Any advice is appreciated.

**Comment by tanem** [comment]
Looks like a dupe (or a response to my question?) of the following issue, so closing and continuing convo there so it's all in one place.

https://github.com/tanem/react-svg/issues/1836
