### ISSUE TITLE
renumerateIRIElements for path defs

### ISSUE THREAD

**Issue by voliva** [tanem/svg-injector#14]
In some of the exported SVGs, inside defs I have something like:

```svg
<defs>
     <path id="a" d="...." />
</defs>
```

Which is then used inside `<g>`, as:

```svg
<g>
    <mask id="b" fill="#fff">
        <use xlink:href="#a" />
    </mask>
    <use fill="#000" xlink:href="#a"/>
    <g mask="url(#b)">
        <path fill="#FFF" d="...."/>
    </g>
</g>
```

When having many elements like these, the svg graphics get mixed up. This example also has the problem of defining the id of the mask outside `<defs>`, and using reference it by id... should I raise a separate issue for that?

**Comment by tanem** [comment]
Thanks for the report @voliva. Any chance you can provide a working repro./example of the problem, so I can make sure I understand what the issue is?

If you like, you can base the example off [this CodeSandbox example](https://codesandbox.io/s/py6oml23wx).

**Comment by voliva** [comment]
Hey @tanem, sorry for taking a while to answer and thank you for taking a look. Sure, here's a [CodeSandbox](https://codesandbox.io/s/k0m40r3w9r) based on yours which reproduces this issue.

Basically, it has 3 icons, and whichever comes the first dictates how the others look. I also added an edited svg (called pollWithUniqueIds) that has the ids manually-replaced by unique ids, and it shows how it does work in that case (It's the current workaround I have)

**Comment by tanem** [comment]
No problem @voliva, and thanks for taking the time to create that example.

Yea it looks like the [`renumerateIRIElements`](https://github.com/tanem/svg-injector/blob/master/src/inject-element.js#L127) section is not dealing with this situation properly. I'll take a closer look as soon as I can and will keep you updated 👍

**Comment by tanem** [comment]
@voliva just opened #15, which contains two commits which fix the issues you're seeing. Feels a bit hacky so just want to think about things for a bit before releasing it, hopefully later today.

Feel free to try the branch out though, any feedback or comments are welcome 🙏

**Comment by tanem** [comment]
Hey @voliva, another update: Have merged #15 into the `3.x` branch, and published that as a beta with the `next` dist-tag. If you want to try it out you can run `npm i @tanem/svg-injector@next`.

**Comment by voliva** [comment]
Thank you so much @tanem! I'm using SVGInjector through `react-svg`, but I'm sure I can hack something to try it out.

**Comment by tanem** [comment]
No problem :+1: Ah right, well let me know how you get on, if need be I can create a `next` version of `react-svg` too.

**Comment by sntran** [comment]
Sorry for touching a closed issue, but this is related. I can open a new issue if needed be.

At the moment, `id` attribute on `<path>` is prefixed with number. This causes issue when trying to querying the `<path>` elements. I understand that this functionality is needed, but can it be limited to elements inside `<defs>`? Correct me if I'm wrong, but most of the time, only those elements are references in `<mask>` and `<use>`.

**Comment by tanem** [comment]
> Sorry for touching a closed issue, but this is related. I can open a new issue if needed be.

No problem, thanks for scanning the issue list first before posting! I _think_ I understand what you're saying, but any chance you can post a code snippet to I can be sure?

Would setting `renumerateIRIElements=false` help your use-case? That option was originally added so you could bypass all that `id` wrangling. Not sure if it's going to be too heavy-handed though 🤔

**Comment by sntran** [comment]
Sure, the easiest example is this SVG: https://upload.wikimedia.org/wikipedia/commons/1/1a/Blank_US_Map_%28states_only%29.svg

Each U.S. states in the map has an `id` attribute. My JS code listens to click event on them to detect which state was selected based on their `id`.

When injected to the page, their `id` changes and my click handler won't work.

Setting `renumerateIRIElements=false` would work, but I do need such functionality for my `<defs>`. If an SVG like the map above also has `<mask>`, then that setting won't work.

But regardless, in my opinion, you would only need to renumerate elements inside `<defs>`. Normal SVG elements outside of it may retain their `id`. Unless it will cause issue.

**Comment by tanem** [comment]
Hey all 👋  The IRI renumeration issues reported here have been fixed in a recent major release. The release also addressed related gaps with style attribute url() references (#1244), <use href> attributes (tanem/react-svg#2671), <style> element text, and compound attribute values.

@sntran: I'll open a separate issue for the defs-only scoping suggestion. For now, `renumerateIRIElements: false` remains the workaround if you need original IDs preserved.
