### ISSUE TITLE
cannot install - not in the registry

### ISSUE THREAD

**Issue by bartekindycki** [tanem/svg-injector#463]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tanem/svg-injector/-/svg-injector-8.0.61.tgz
 npm ERR! 404 
 npm ERR! 404  '@tanem/svg-injector@8.0.61' is not in the npm registry.
 npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
 npm ERR! 404 
 npm ERR! 404 Note that you can also install from a
 npm ERR! 404 tarball, folder, http url, or git url.
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2020-08-06T08_58_33_447Z-debug.log

**Comment by Xingo123** [comment]
Same problem here.

**Comment by sunnyofhell** [comment]
error Couldn't find package "@tanem/svg-injector@^1.2.1" required by "react-svg@^5.0.14" on the "npm" registry.

Same problem causing all builds to fail, on Local and AWS.

**Comment by Xingo123** [comment]
I've already deleted React-SVG from our solution. We couldn't wait till this is fixed. Our builds are now succeeded and our applications are now deploying. So a quick solution is to delete ReactSVG. 

Good luck everyone!

**Comment by molakos** [comment]
I just re-ran our deployment and it succeeded without any errors. Let's hope that this won't occur again.

**Comment by bartekindycki** [comment]
It works for me now.

**Comment by sunnyofhell** [comment]
yup. it just started working.

**Comment by tanem** [comment]
Hey folks,

Looks like there was an issue with npm around that time that would have affected installs of this scoped package: [Issues accessing npmjs.com and installing scoped packages](https://status.npmjs.org/incidents/cksjqc1w11v5?u=mdkvwtx1zxnn).

It was resolved on their side after a period of time, which likely explains why things suddenly started working again.
