### ISSUE TITLE
Cookie: token value is not adding while image call

### ISSUE THREAD

**Issue by Sgajjar08** [tanem/svg-injector#792]
Hello tanem,

We are using image calls to have an image and I am using (load)="SVGInjector()". Although we are setting the token for the call in cookies and in the request header it should pass the token but it seems like it's not. Do you have a solution for it? (we tried by putting httpRequest.withCredentials = true; in file https://github.com/tanem/svg-injector/blob/master/src/make-ajax-request.ts) and it works so do we have another version where we can have something like this?

**Comment by tanem** [comment]
Fix released in 10.1.0. See linked PR for discussion.

Thanks for the enhancement @Sgajjar08 🎉
