### ISSUE TITLE
Can't import in browser

### ISSUE THREAD

**Issue by sntran** [tanem/svg-injector#9]
For ESM module, you currently have this:

```es6
import SVGInjector from './svg-injector';
export default SVGInjector;
```

While this can be resolved to `/svg-injector.js`, when using as ES6 module, the browser can't resolve and won't import the library.

Please consider adding `.js` to all your imports, either manually or through babel.

**Comment by tanem** [comment]
Thanks for reporting @sntran :pray:

Took the easy option for now and manually added `.js`. Have just released version `2.0.3` with [the fix](#10) if you want to check it out before I resolve the issue?

**Comment by sntran** [comment]
👍 Awesome. It works great. Thank you for fixing so quick.

**Comment by tanem** [comment]
Great 🎉No problem @sntran.
